### ISSUE TITLE
Meta-tile support

### ISSUE THREAD

**Issue by dBitech** [CrunchyData/pg_tileserv#16]
Just leaving this here as a Feature request.  Support Metata tiles as a ay to cut down on the number of network requests that are needed. 

A couple of articles from @mojodna:
https://medium.com/@mojodna/tapalcatl-cloud-optimized-tile-archives-1db8d4577d92
https://medium.com/@mojodna/tapalcatl-2-updates-8eb827d969c1 

and a cache implementation already written, that may work as additional background.
https://github.com/tierpod/metatiles-cacher/tree/master/pkg/metatile

**Comment by douglasg14b** [comment]
This is essentially on-disk tile cache support right?

if so, this would be very valuable, and would save on extra HTTP requests between services if this was integrated into this project.

**Comment by pramsey** [comment]
This seems fairly orthogonal to the goal of providing dynamic access to database features in a vector file format. The cute trick of zipping up tiles and putting them into an HTTP bucket and then using HTTP offset reads to randomly access particular tiles doesn't map to dynamically generating tiles.

**Comment by douglasg14b** [comment]
Eh, caching the tiles is somewhat necessary, dynamic or not. Unless you have a very volatile dataset, there will be plenty of tiles that may not see changes, but are requested often. It's a waste of resources to put that load on postgress no?

I don't see how cache is orthogonal to dynamic tiles.

I can, however, see the meta tile idea (or as you most contemptuously put it, "the cute trick") not necessarily being a great target over a more simple caching mechanism.

**Comment by pramsey** [comment]
Well, the goal is for the tile service to be as small as possible, on the theory that the "correct" modern way to build a service-out-of-microservices is to chain together the parts you need. So, [pg_tileserv] => [varnish cache] => [public internet]. Or, for folks needing auth, pg_tileserv] => [keycloak proxy] => [varnish cache] => [public internet].

If we figure that the tileserver needs to be able to survive naked on the public internet, then it has to include a lot of extra functionality (auth, cache, etc) that will be (a) duplicative of other specialty system and (b) probably not done as well.

I feel like *most* of the utility of metatiling is in the world of raster tiles, since metatiles do a nice job of handling things like label/border and style/border conflicts. For getting "more features per HTTP file request" I wonder if maybe configuring the tile resolution to be sharper and your tile client to hop more aggressively down the tile stack might be a smaller tweak to the tile model than a wholesale extra "meta mode".
