### ISSUE TITLE
Expand jsonb properties in tilejson

### ISSUE THREAD

**Issue by tordans** [CrunchyData/pg_tileserv#178]
We use osm2pgsql with the handy feature to push properties in jsonb fields.

Our tilejson looks like the one below.

When I preview the features, the jsonb fields are "flattened" in a regular key-value-pair.

Would it be possible to do the same here? My understanding is, the tilejson should mimic what I see when using the tiles, which is not a jsonb-field but the flattened version of that.

```json
  "properties": [
    {
      "name": "osm_type",
      "type": "bpchar",
      "description": ""
    },
    {
      "name": "osm_id",
      "type": "int8",
      "description": ""
    },
    {
      "name": "tags",
      "type": "jsonb",
      "description": ""
    },
    {
      "name": "meta",
      "type": "jsonb",
      "description": ""
    }
  ],
```

**Comment by pramsey** [comment]
no, it's not really possible because the jsonb doesn't have a schema in the same way that the table data. I can get a guaranteed 100% correct list of columns and types of a table from the Pg system catalog. I can pull the first item out of a jsonb column and read the key names, but that gives me 0% guarantee that all other objects will have those same keys. I could have spares. I could be missing some. The MVT format is just a K/V format, so we can include different janky lists of properties in the tiles and it fits the tile contract. Not so for the jsonb.
