### ISSUE TITLE
Leafletjs + pg_tileserve and protobuf layer yield string value instead of numeric for property?

### ISSUE THREAD

**Issue by Jan-M** [CrunchyData/pg_tileserv#55]
Hi again,

I copied a leaflet example to do some dynamic styling on a kpi field returned via protobuf from my table layer.

The meta data provided by pg_tileserv looks good, it indicates that the field is numeric.

`{"name":"kpi","type":"numeric","description":""}`

Yet when I access this later to style via `properties.kpi` I get a String value in Javascript.

Is this a tileserv issue? Dont know how to inspect the protobuf response.

Thanks!

**Comment by pramsey** [comment]
Might actually be a PostGIS issue, since that's where the MVT gets generated. One problem with trying to coerce a numeric into something like a double (which wouldn't be a completely bad thing) is that it's possible to have unconstrained large values in numeric. So you can loose fidelity if you do that. 

Looking at the PostGIS source, I can confirm that numeric are treated with default handling, so they are placed in string values. There's actually differently handling in the case where the function is fed jsonb attributes, which does a dynamic thing to see if the numeric is integral or not and uses the appropriate type for each case. 

A ticket in PostGIS land about handling numeric as a number would be the next step.

**Comment by Jan-M** [comment]
Hi Paul,

I appreciate the quick and helpful response. You are right, this sounds like it is correct given the precision limitation. Gonna go for float/double now which is fine for me.

Otherwise it does work great, discovering a new side of Postgres as I go.

-- Jan
