### ISSUE TITLE
New features not available until landing page refresh

### ISSUE THREAD

**Issue by reyemtm** [CrunchyData/pg_tileserv#57]
Not sure if this is a bug or intentional. Seems to be the same situation with featureserv as well.

### Steps

1. Start pg_tileserv
1. Give a new postgres feature the proper permissions to be accessed by pg_tileserv
2. Attempt to access feature in Mapbox map
3. Returns 500
4. Refresh main landing page of pg_tileserv showing "Available Layers"
5. Refresh Mapbox map
6. Success

Is there a way to force a new connection or refresh the connection when a feature is not found, or is this the default and expected behavior?

*This instance of pg_tileserv is proxied if that matters.*

**Comment by dr-jts** [comment]
This is by design.  For efficiency the catalog of layers is loaded and cached. So it needs some event to trigger reloading the cache.  At the moment it is triggered by a request to the landing page.  

`pg_featureserv` works in the same way.

The expectation is that implementations will know best when to trigger a refresh (which they can do by hitting the landing page URL).

**Comment by reyemtm** [comment]
Thanks for the clarification.
