### ISSUE TITLE
pg_tileserv and QGIS?

### ISSUE THREAD

**Issue by sfkeller** [CrunchyData/pg_tileserv#79]
Question:
  
Can pg_tileserv be configured to work with new Vector Tile connection of QGIS 3.18+?

P.S. This question is goal-wise related with this issue https://github.com/CrunchyData/pg_featureserv/issues/63 .

**Comment by wesnick** [comment]
Yes, I was using this feature yesterday. It works out of the box.  All you need to do is supply the tileurl.

**Comment by MatzeHa** [comment]
Hello,
unfortunately, it does not work for me. pg_tileserv works fine when I look at the data in the browser, but when I establish the vector tiles connection in QGIS, I can add the table-layers and function layers to the map, but nothing is shown. Also, the layers don't seem to have attribute tables. I know, something is happening, because the EPSG adapts to the EPSG of the database. Also, when adding them to the map no error is shown. But after days of trying, still nothing is drawn to the map.

I'd appreciate any ideas, why this is not working for me!
