### ISSUE TITLE
pg_tileserv does not find this source if  type  of  field geometry

### ISSUE THREAD

**Issue by Barolina** [CrunchyData/pg_tileserv#86]
why if I create a field type that is not geometry(Polygon, 4326), and only geometry. pg_tileserv does not find this source

example
```
CREATE TABLE public.landmark (
	id serial NOT NULL,
	"name" text NULL,
	"type" text NULL,
	"location" geometry NULL,
	geom geometry NULL,
	CONSTRAINT landmark_pkey PRIMARY KEY (id)
);

```

**Comment by pramsey** [comment]
The system needs to project the data in the table into the target spatial reference system for the tiles, and it cannot do that without knowing the source reference system. Since you are not providing that in the table definition, we just skip that table: without the source SRS, it is not publishable.
